services:
    web:
        build:
            context: ./web
        dns:
            - 127.0.0.11 # Docker interne
            - 8.8.8.8
            - 1.1.1.1
        ports:
            - "3000:3000"
        environment:
            - MUSIC_SERVER_URL=http://server:4000
            - AUTH_URL=${AUTH_URL}
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
            - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
            - LASTFM_API_KEY=${LASTFM_API_KEY}
        depends_on:
            - server
        restart: unless-stopped

    server:
        build:
            context: ./server
        expose:
            - "4000"
        dns:
            - 127.0.0.11 # Docker interne
            - 8.8.8.8
            - 1.1.1.1
        volumes:
            - ${XDG_RUNTIME_DIR:-/run/user/1000}/pulse:${XDG_RUNTIME_DIR:-/run/user/1000}/pulse
            - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie:ro
            - spotosh-data:/data
        environment:
            - DATA_DIR=/data
            - PORT=4000
            - PULSE_SERVER=unix:${XDG_RUNTIME_DIR:-/run/user/1000}/pulse/native
            - PULSE_COOKIE=/root/.config/pulse/cookie
        restart: unless-stopped
        devices:
            - /dev/snd:/dev/snd

volumes:
    spotosh-data:
